version: '3.8'

services:
  mysql-container:
    image: mysql:latest
    container_name: mysqldb1
    env_file:
      - ./config.yaml
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql

#sudo docker exec -it mysqldb1 mysql -u root -p
#